name: CI - Crystal
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci-crystal.yml'
      - 'spec/**'
      - 'src/**'
      - 'shard.yml'
      - 'shard.lock'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    paths:
      - '.github/workflows/ci-crystal.yml'
      - 'spec/**'
      - 'src/**'
      - 'shard.yml'
      - 'shard.lock'
      - 'package.json'
      - 'package-lock.json'

jobs:
  spec:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crystal-lang/install-crystal@v1
      # Need node.js to install validator. Spec includes the validator runner
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: crystal spec
