name: CI - Crystal
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci-crystal.yml'
      - 'spec/**'
      - 'src/**'
      - 'shard.yml'
      - 'shard.lock'
  pull_request:
    paths:
      - '.github/workflows/ci-crystal.yml'
      - 'spec/**'
      - 'src/**'
      - 'shard.yml'
      - 'shard.lock'

jobs:
  spec:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crystal-lang/install-crystal@v1
      - run: crystal spec
