name: CI
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci.yml'
      - '**/*.json'
      - '**/*.json5'
      - 'scripts/validator.cr'
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - '**/*.json'
      - '**/*.json5'
      - 'scripts/validator.cr'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install dependencies
        run: npm install
      - uses: crystal-lang/install-crystal@v1
      - name: Validate
        run: crystal run scripts/validator.cr
